[2023-06-30T04:19:26.721+0100] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: using_taskflow_v2.greet scheduled__0029-07-09T00:00:00+00:00 [queued]>
[2023-06-30T04:19:26.731+0100] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: using_taskflow_v2.greet scheduled__0029-07-09T00:00:00+00:00 [queued]>
[2023-06-30T04:19:26.732+0100] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-06-30T04:19:26.755+0100] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): greet> on 0029-07-09 00:00:00+00:00
[2023-06-30T04:19:26.759+0100] {standard_task_runner.py:57} INFO - Started process 29985 to run task
[2023-06-30T04:19:26.764+0100] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'using_taskflow_v2', 'greet', 'scheduled__0029-07-09T00:00:00+00:00', '--job-id', '200', '--raw', '--subdir', '/home/haboubi/Desktop/api/API_weather/dags/dag_create_py_api_taskflow.py', '--cfg-path', '/tmp/tmpi0_5b_f7']
[2023-06-30T04:19:26.768+0100] {standard_task_runner.py:85} INFO - Job 200: Subtask greet
[2023-06-30T04:19:26.822+0100] {task_command.py:410} INFO - Running <TaskInstance: using_taskflow_v2.greet scheduled__0029-07-09T00:00:00+00:00 [running]> on host haboubi-VivoBook-15-ASUS-Laptop-X540UB
[2023-06-30T04:19:26.877+0100] {abstractoperator.py:594} ERROR - Exception rendering Jinja template for task 'greet', field 'op_kwargs'. Template: {'name': XComArg(<Task(_PythonDecoratedOperator): get_name>, 'first_name'), 'prenom': XComArg(<Task(_PythonDecoratedOperator): get_name>, 'last_name'), 'age': XComArg(<Task(_PythonDecoratedOperator): get_age>)}
Traceback (most recent call last):
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 586, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/template/templater.py", line 168, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/template/templater.py", line 168, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/template/templater.py", line 158, in render_template
    return value.resolve(context)
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/models/xcom_arg.py", line 373, in resolve
    raise XComNotFound(ti.dag_id, task_id, self.key)
airflow.exceptions.XComNotFound: XComArg result from get_name at using_taskflow_v2 with key="first_name" is not found!
[2023-06-30T04:19:26.888+0100] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1407, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1531, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2179, in render_templates
    original_task.render_template_fields(context)
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1254, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 586, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/template/templater.py", line 168, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/template/templater.py", line 168, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/template/templater.py", line 158, in render_template
    return value.resolve(context)
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/models/xcom_arg.py", line 373, in resolve
    raise XComNotFound(ti.dag_id, task_id, self.key)
airflow.exceptions.XComNotFound: XComArg result from get_name at using_taskflow_v2 with key="first_name" is not found!
[2023-06-30T04:19:26.893+0100] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=using_taskflow_v2, task_id=greet, execution_date=290709T000000, start_date=20230630T031926, end_date=20230630T031926
[2023-06-30T04:19:26.909+0100] {standard_task_runner.py:104} ERROR - Failed to execute job 200 for task greet (XComArg result from get_name at using_taskflow_v2 with key="first_name" is not found!; 29985)
[2023-06-30T04:19:26.938+0100] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-30T04:19:26.958+0100] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-06-30T04:21:32.965+0100] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: using_taskflow_v2.greet scheduled__0029-07-09T00:00:00+00:00 [queued]>
[2023-06-30T04:21:32.971+0100] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: using_taskflow_v2.greet scheduled__0029-07-09T00:00:00+00:00 [queued]>
[2023-06-30T04:21:32.971+0100] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-06-30T04:21:32.982+0100] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): greet> on 0029-07-09 00:00:00+00:00
[2023-06-30T04:21:32.985+0100] {standard_task_runner.py:57} INFO - Started process 31492 to run task
[2023-06-30T04:21:32.988+0100] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'using_taskflow_v2', 'greet', 'scheduled__0029-07-09T00:00:00+00:00', '--job-id', '198', '--raw', '--subdir', '/home/haboubi/Desktop/api/API_weather/dags/dag_create_py_api_taskflow.py', '--cfg-path', '/tmp/tmpho3cs_0y']
[2023-06-30T04:21:32.989+0100] {standard_task_runner.py:85} INFO - Job 198: Subtask greet
[2023-06-30T04:21:33.017+0100] {task_command.py:410} INFO - Running <TaskInstance: using_taskflow_v2.greet scheduled__0029-07-09T00:00:00+00:00 [running]> on host haboubi-VivoBook-15-ASUS-Laptop-X540UB
[2023-06-30T04:21:33.072+0100] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='haboubi' AIRFLOW_CTX_DAG_ID='using_taskflow_v2' AIRFLOW_CTX_TASK_ID='greet' AIRFLOW_CTX_EXECUTION_DATE='0029-07-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__0029-07-09T00:00:00+00:00'
[2023-06-30T04:21:33.073+0100] {logging_mixin.py:149} INFO - hello my name is fadi hello my prenom is haboubi and im 18 years old
[2023-06-30T04:21:33.073+0100] {python.py:183} INFO - Done. Returned value was: None
[2023-06-30T04:21:33.076+0100] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=using_taskflow_v2, task_id=greet, execution_date=290709T000000, start_date=20230630T032132, end_date=20230630T032133
[2023-06-30T04:21:33.119+0100] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-30T04:21:33.130+0100] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
