[2023-06-30T04:14:42.590+0100] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: using_taskflow_v1.greet scheduled__0029-06-29T00:00:00+00:00 [queued]>
[2023-06-30T04:14:42.601+0100] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: using_taskflow_v1.greet scheduled__0029-06-29T00:00:00+00:00 [queued]>
[2023-06-30T04:14:42.602+0100] {taskinstance.py:1308} INFO - Starting attempt 1 of 6
[2023-06-30T04:14:42.621+0100] {taskinstance.py:1327} INFO - Executing <Task(_PythonDecoratedOperator): greet> on 0029-06-29 00:00:00+00:00
[2023-06-30T04:14:42.623+0100] {standard_task_runner.py:57} INFO - Started process 27237 to run task
[2023-06-30T04:14:42.627+0100] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'using_taskflow_v1', 'greet', 'scheduled__0029-06-29T00:00:00+00:00', '--job-id', '169', '--raw', '--subdir', '/home/haboubi/Desktop/api/API_weather/dags/dag_create_py_api_taskflow.py', '--cfg-path', '/tmp/tmpyq74uf2t']
[2023-06-30T04:14:42.629+0100] {standard_task_runner.py:85} INFO - Job 169: Subtask greet
[2023-06-30T04:14:42.685+0100] {task_command.py:410} INFO - Running <TaskInstance: using_taskflow_v1.greet scheduled__0029-06-29T00:00:00+00:00 [running]> on host haboubi-VivoBook-15-ASUS-Laptop-X540UB
[2023-06-30T04:14:42.733+0100] {abstractoperator.py:594} ERROR - Exception rendering Jinja template for task 'greet', field 'op_kwargs'. Template: {'name': XComArg(<Task(_PythonDecoratedOperator): get_name>, '1'), 'prenom': XComArg(<Task(_PythonDecoratedOperator): get_name>, '2'), 'age': XComArg(<Task(_PythonDecoratedOperator): get_age>)}
Traceback (most recent call last):
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 586, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/template/templater.py", line 168, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/template/templater.py", line 168, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/template/templater.py", line 158, in render_template
    return value.resolve(context)
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/models/xcom_arg.py", line 373, in resolve
    raise XComNotFound(ti.dag_id, task_id, self.key)
airflow.exceptions.XComNotFound: XComArg result from get_name at using_taskflow_v1 with key="1" is not found!
[2023-06-30T04:14:42.740+0100] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1407, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1531, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2179, in render_templates
    original_task.render_template_fields(context)
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1254, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 586, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/template/templater.py", line 168, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/template/templater.py", line 168, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/template/templater.py", line 158, in render_template
    return value.resolve(context)
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/models/xcom_arg.py", line 373, in resolve
    raise XComNotFound(ti.dag_id, task_id, self.key)
airflow.exceptions.XComNotFound: XComArg result from get_name at using_taskflow_v1 with key="1" is not found!
[2023-06-30T04:14:42.745+0100] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=using_taskflow_v1, task_id=greet, execution_date=290629T000000, start_date=20230630T031442, end_date=20230630T031442
[2023-06-30T04:14:42.757+0100] {standard_task_runner.py:104} ERROR - Failed to execute job 169 for task greet (XComArg result from get_name at using_taskflow_v1 with key="1" is not found!; 27237)
[2023-06-30T04:14:42.799+0100] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-30T04:14:42.819+0100] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
