[2023-07-03T16:26:10.783+0100] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: updated_day_hist.load_updated_data scheduled__2023-07-01T00:00:00+00:00 [queued]>
[2023-07-03T16:26:10.793+0100] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: updated_day_hist.load_updated_data scheduled__2023-07-01T00:00:00+00:00 [queued]>
[2023-07-03T16:26:10.793+0100] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2023-07-03T16:26:10.806+0100] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): load_updated_data> on 2023-07-01 00:00:00+00:00
[2023-07-03T16:26:10.810+0100] {standard_task_runner.py:57} INFO - Started process 15228 to run task
[2023-07-03T16:26:10.813+0100] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'updated_day_hist', 'load_updated_data', 'scheduled__2023-07-01T00:00:00+00:00', '--job-id', '56', '--raw', '--subdir', '/home/haboubi/Desktop/api/API_weather/dags/update_day_hist.py', '--cfg-path', '/tmp/tmpw7ckm2uz']
[2023-07-03T16:26:10.814+0100] {standard_task_runner.py:85} INFO - Job 56: Subtask load_updated_data
[2023-07-03T16:26:10.887+0100] {task_command.py:410} INFO - Running <TaskInstance: updated_day_hist.load_updated_data scheduled__2023-07-01T00:00:00+00:00 [running]> on host haboubi-VivoBook-15-ASUS-Laptop-X540UB
[2023-07-03T16:26:11.015+0100] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='haboubi' AIRFLOW_CTX_DAG_ID='updated_day_hist' AIRFLOW_CTX_TASK_ID='load_updated_data' AIRFLOW_CTX_EXECUTION_DATE='2023-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-01T00:00:00+00:00'
[2023-07-03T16:26:11.030+0100] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/haboubi/Desktop/api/API_weather/api_env/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/haboubi/Desktop/api/API_weather/dags/update_day_hist.py", line 47, in load_updated_data_db
    loc=session.query(Location).filter_by(Location.name==locations_csv.iloc[i]['name']).first()
TypeError: Query.filter_by() takes 1 positional argument but 2 were given
[2023-07-03T16:26:11.047+0100] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=updated_day_hist, task_id=load_updated_data, execution_date=20230701T000000, start_date=20230703T152610, end_date=20230703T152611
[2023-07-03T16:26:11.061+0100] {standard_task_runner.py:104} ERROR - Failed to execute job 56 for task load_updated_data (Query.filter_by() takes 1 positional argument but 2 were given; 15228)
[2023-07-03T16:26:11.105+0100] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-07-03T16:26:11.141+0100] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-07-03T16:48:59.058+0100] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: updated_day_hist.load_updated_data scheduled__2023-07-01T00:00:00+00:00 [queued]>
[2023-07-03T16:48:59.068+0100] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: updated_day_hist.load_updated_data scheduled__2023-07-01T00:00:00+00:00 [queued]>
[2023-07-03T16:48:59.068+0100] {taskinstance.py:1308} INFO - Starting attempt 1 of 3
[2023-07-03T16:48:59.079+0100] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): load_updated_data> on 2023-07-01 00:00:00+00:00
[2023-07-03T16:48:59.085+0100] {standard_task_runner.py:57} INFO - Started process 23235 to run task
[2023-07-03T16:48:59.089+0100] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'updated_day_hist', 'load_updated_data', 'scheduled__2023-07-01T00:00:00+00:00', '--job-id', '91', '--raw', '--subdir', '/home/haboubi/Desktop/api/API_weather/dags/update_day_hist.py', '--cfg-path', '/tmp/tmp89ndq1uu']
[2023-07-03T16:48:59.090+0100] {standard_task_runner.py:85} INFO - Job 91: Subtask load_updated_data
[2023-07-03T16:48:59.158+0100] {task_command.py:410} INFO - Running <TaskInstance: updated_day_hist.load_updated_data scheduled__2023-07-01T00:00:00+00:00 [running]> on host haboubi-VivoBook-15-ASUS-Laptop-X540UB
[2023-07-03T16:48:59.267+0100] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='haboubi' AIRFLOW_CTX_DAG_ID='updated_day_hist' AIRFLOW_CTX_TASK_ID='load_updated_data' AIRFLOW_CTX_EXECUTION_DATE='2023-07-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-01T00:00:00+00:00'
[2023-07-03T16:48:59.274+0100] {logging_mixin.py:149} INFO - debug prb: Paris
[2023-07-03T16:48:59.303+0100] {logging_mixin.py:149} INFO - debug prb: London
[2023-07-03T16:48:59.314+0100] {logging_mixin.py:149} INFO - debug prb: Barcelona
[2023-07-03T16:48:59.324+0100] {logging_mixin.py:149} INFO - debug prb: Rome
[2023-07-03T16:48:59.333+0100] {logging_mixin.py:149} INFO - debug prb: New York
[2023-07-03T16:48:59.342+0100] {logging_mixin.py:149} INFO - debug prb: Tokyo
[2023-07-03T16:48:59.352+0100] {logging_mixin.py:149} INFO - debug prb: Istanbul
[2023-07-03T16:48:59.361+0100] {logging_mixin.py:149} INFO - debug prb: Dubai
[2023-07-03T16:48:59.372+0100] {logging_mixin.py:149} INFO - debug prb: Sydney
[2023-07-03T16:48:59.381+0100] {logging_mixin.py:149} INFO - debug prb: Bangkok
[2023-07-03T16:48:59.390+0100] {logging_mixin.py:149} INFO - debug prb: Amsterdam
[2023-07-03T16:48:59.399+0100] {logging_mixin.py:149} INFO - debug prb: Rio De Janeiro
[2023-07-03T16:48:59.408+0100] {logging_mixin.py:149} INFO - debug prb: Prague
[2023-07-03T16:48:59.418+0100] {logging_mixin.py:149} INFO - debug prb: Cape Town
[2023-07-03T16:48:59.426+0100] {logging_mixin.py:149} INFO - debug prb: Buenos Aires
[2023-07-03T16:48:59.436+0100] {logging_mixin.py:149} INFO - debug prb: Singapore
[2023-07-03T16:48:59.445+0100] {logging_mixin.py:149} INFO - debug prb: Florence
[2023-07-03T16:48:59.454+0100] {logging_mixin.py:149} INFO - debug prb: San Francisco
[2023-07-03T16:48:59.463+0100] {logging_mixin.py:149} INFO - debug prb: Marrakech
[2023-07-03T16:48:59.473+0100] {logging_mixin.py:149} INFO - debug prb: Berlin
[2023-07-03T16:48:59.483+0100] {python.py:183} INFO - Done. Returned value was: 0
[2023-07-03T16:48:59.521+0100] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=updated_day_hist, task_id=load_updated_data, execution_date=20230701T000000, start_date=20230703T154859, end_date=20230703T154859
[2023-07-03T16:48:59.541+0100] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-07-03T16:48:59.570+0100] {taskinstance.py:2653} INFO - 1 downstream tasks scheduled from follow-on schedule check
